apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: employee-app
type: Opaque
stringData:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  DB_USER: cG9zdGdyZXM=
  DB_PASSWORD: cG9zdGdyZXM=
   
