apiVersion: networking.k8s.io/vi
kind: Ingress
metadata:
  name: employee-ingress 
  namespace: employee-app 
spec: 
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80